-- Create the database if it doesn't exist
CREATE DATABASE IF NOT EXISTS pharmacy;
USE pharmacy;

-- Drop existing tables if they exist (in the correct order to avoid foreign key issues)
DROP TABLE IF EXISTS sales;
DROP TABLE IF EXISTS purchases;
DROP TABLE IF EXISTS medicines_stock;
DROP TABLE IF EXISTS medicines;
DROP TABLE IF EXISTS invoices;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS suppliers;
DROP TABLE IF EXISTS admin_credentials;

-- 1. Create admin_credentials table
CREATE TABLE IF NOT EXISTS admin_credentials (
  USERNAME VARCHAR(50) NOT NULL,
  PASSWORD VARCHAR(50) NOT NULL,
  IS_LOGGED_IN BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (USERNAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2. Create customers table
CREATE TABLE IF NOT EXISTS customers (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  CONTACT_NUMBER VARCHAR(15) NOT NULL,
  ADDRESS VARCHAR(255) NOT NULL,
  DOCTOR_NAME VARCHAR(100) NOT NULL,
  DOCTOR_ADDRESS VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 3. Create suppliers table
CREATE TABLE IF NOT EXISTS suppliers (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL,
  CONTACT_NUMBER VARCHAR(15) NOT NULL,
  ADDRESS VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 4. Create invoices table
CREATE TABLE IF NOT EXISTS invoices (
  INVOICE_ID INT AUTO_INCREMENT PRIMARY KEY,
  NET_TOTAL DOUBLE NOT NULL DEFAULT 0,
  INVOICE_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CUSTOMER_ID INT NOT NULL,
  TOTAL_AMOUNT DOUBLE NOT NULL,
  TOTAL_DISCOUNT DOUBLE NOT NULL,
  FOREIGN KEY (CUSTOMER_ID) REFERENCES customers(ID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 5. Create medicines table
CREATE TABLE IF NOT EXISTS medicines (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  PACKING VARCHAR(20) NOT NULL,
  GENERIC_NAME VARCHAR(100) NOT NULL,
  SUPPLIER_NAME VARCHAR(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 6. Create medicines_stock table with EXPIRY_DATE as VARCHAR to store MM/YY
CREATE TABLE IF NOT EXISTS medicines_stock (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  BATCH_ID VARCHAR(20) NOT NULL UNIQUE,
  EXPIRY_DATE VARCHAR(5) NOT NULL, -- Stores expiry date as MM/YY
  QUANTITY INT NOT NULL,
  MRP DOUBLE NOT NULL,
  RATE DOUBLE NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 7. Create purchases table
CREATE TABLE IF NOT EXISTS purchases (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  VOUCHER_NUMBER VARCHAR(50) NOT NULL,
  SUPPLIER_ID INT,
  SUPPLIER_NAME VARCHAR(100) DEFAULT NULL,
  INVOICE_NUMBER VARCHAR(50) NOT NULL,
  PURCHASE_DATE DATE NOT NULL,
  TOTAL_AMOUNT DOUBLE NOT NULL DEFAULT 0,
  PAYMENT_STATUS VARCHAR(20) NOT NULL,
  FOREIGN KEY (SUPPLIER_ID) REFERENCES suppliers(ID) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 8. Create sales table
CREATE TABLE IF NOT EXISTS sales (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  INVOICE_NUMBER INT NOT NULL,
  CUSTOMER_ID INT NOT NULL,
  MEDICINE_NAME VARCHAR(100) NOT NULL,
  BATCH_ID VARCHAR(20) NOT NULL,
  EXPIRY_DATE VARCHAR(5) NOT NULL, -- Stores expiry date as MM/YY
  QUANTITY INT NOT NULL,
  MRP DOUBLE NOT NULL,
  DISCOUNT DOUBLE NOT NULL,
  TOTAL DOUBLE NOT NULL,
  FOREIGN KEY (INVOICE_NUMBER) REFERENCES invoices(INVOICE_ID) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (CUSTOMER_ID) REFERENCES customers(ID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Insert sample data after creating all tables
INSERT INTO admin_credentials (USERNAME, PASSWORD) VALUES ('admin', 'admin12');

INSERT INTO customers (NAME, CONTACT_NUMBER, ADDRESS, DOCTOR_NAME, DOCTOR_ADDRESS) VALUES
('Ali Khan', '03001234567', 'Karachi', 'Dr. Ahmed', 'Karachi'),
('Fatima Bibi', '03123456789', 'Lahore', 'Dr. Saeed', 'Lahore'),
('Zainab Ali', '03234567890', 'Islamabad', 'Dr. Khan', 'Islamabad'),
('Omar Farooq', '03345678901', 'Peshawar', 'Dr. Rizwan', 'Peshawar'),
('Sara Ahmed', '03456789012', 'Quetta', 'Dr. Bilal', 'Quetta');

INSERT INTO suppliers (NAME, EMAIL, CONTACT_NUMBER, ADDRESS) VALUES
('Pak Pharma', 'pakpharma@gmail.com', '03456789012', 'Karachi'),
('Al-Madina Pharma', 'almadina@gmail.com', '03567890123', 'Lahore'),
('Khan Pharma', 'khanpharma@gmail.com', '03678901234', 'Islamabad');

INSERT INTO medicines (NAME, PACKING, GENERIC_NAME, SUPPLIER_NAME) VALUES
('Paracetamol', '10tab', 'Paracetamol', 'Pak Pharma'),
('Ibuprofen', '10tab', 'Ibuprofen', 'Khan Pharma'),
('Aspirin', '15tab', 'Aspirin', 'Al-Madina Pharma'),
('Gelusil', '10tab', 'Antacid', 'Pak Pharma');

-- Insert sample data for medicines_stock with expiry as MM/YY format
INSERT INTO medicines_stock (NAME, BATCH_ID, EXPIRY_DATE, QUANTITY, MRP, RATE) VALUES
('Ibuprofen', 'IBU123', '12/25', 50, 100, 80),
('Gelusil', 'GEL456', '11/24', 30, 50, 40),
('Aspirin', 'ASP789', '01/26', 20, 60, 50),
('Paracetamol', 'PAR101', '05/23', 100, 30, 25);

INSERT INTO invoices (NET_TOTAL, INVOICE_DATE, CUSTOMER_ID, TOTAL_AMOUNT, TOTAL_DISCOUNT) VALUES
(100, '2024-11-14', 5, 95, 5),
(120, '2023-11-02', 2, 115, 5);

INSERT INTO purchases (VOUCHER_NUMBER, SUPPLIER_ID, SUPPLIER_NAME, INVOICE_NUMBER, PURCHASE_DATE, TOTAL_AMOUNT, PAYMENT_STATUS) VALUES
('VOUCH001', 1, 'Pak Pharma', 'INV001', '2023-10-10', 2000, 'PAID');

-- Insert sample data for sales with expiry as MM/YY format
INSERT INTO sales (INVOICE_NUMBER, CUSTOMER_ID, MEDICINE_NAME, BATCH_ID, EXPIRY_DATE, QUANTITY, MRP, DISCOUNT, TOTAL) VALUES
(1, 5, 'Ibuprofen', 'IBU123', '12/25', 2, 100, 0, 200);

COMMIT;
